# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File_cabinet_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow_fc(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 716)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(240, 235, 190)\n"
"}\n"
"QPushButton{\n"
"    background-color:rgb(182, 217, 157);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;        \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(147, 204, 105);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px    \n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(690, 70, 321, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reg_but = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reg_but.setObjectName("reg_but")
        self.verticalLayout_3.addWidget(self.reg_but)
        self.choose_but = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.choose_but.setObjectName("choose_but")
        self.verticalLayout_3.addWidget(self.choose_but)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 671, 621))
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(131)
        self.main_but = QtWidgets.QPushButton(self.centralwidget)
        self.main_but.setGeometry(QtCore.QRect(10, 20, 171, 29))
        self.main_but.setObjectName("main_but")
        self.ch_label = QtWidgets.QLabel(self.centralwidget)
        self.ch_label.setGeometry(QtCore.QRect(700, 320, 301, 131))
        self.ch_label.setText("")
        self.ch_label.setObjectName("ch_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FilEye"))
        self.reg_but.setText(_translate("MainWindow", "New user"))
        self.choose_but.setText(_translate("MainWindow", "Select"))
        self.main_but.setText(_translate("MainWindow", "Main window"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow_fc()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
