# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1669, 975)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/poop-shit-poo-cream-ice-2_108504.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("poop-shit-poo-cream-ice-2_108504.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(240, 235, 190)\n"
"}\n"
"QPushButton{\n"
"    background-color:rgb(182, 217, 157);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;        \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(147, 204, 105);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px    \n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 275, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_port_but = QtWidgets.QPushButton(self.layoutWidget)
        self.open_port_but.setObjectName("open_port_but")
        self.horizontalLayout.addWidget(self.open_port_but)
        self.close_port_but = QtWidgets.QPushButton(self.layoutWidget)
        self.close_port_but.setObjectName("close_port_but")
        self.horizontalLayout.addWidget(self.close_port_but)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 140, 361, 321))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 40, 301, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.red_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.red_slider.setMaximum(255)
        self.red_slider.setOrientation(QtCore.Qt.Vertical)
        self.red_slider.setObjectName("red_slider")
        self.horizontalLayout_2.addWidget(self.red_slider)
        self.green_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.green_slider.setMaximum(255)
        self.green_slider.setOrientation(QtCore.Qt.Vertical)
        self.green_slider.setObjectName("green_slider")
        self.horizontalLayout_2.addWidget(self.green_slider)
        self.blue_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.blue_slider.setMaximum(255)
        self.blue_slider.setOrientation(QtCore.Qt.Vertical)
        self.blue_slider.setObjectName("blue_slider")
        self.horizontalLayout_2.addWidget(self.blue_slider)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 290, 241, 19))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(100, 260, 211, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spinBox_red = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_red.setMaximum(255)
        self.spinBox_red.setObjectName("spinBox_red")
        self.horizontalLayout_5.addWidget(self.spinBox_red)
        self.spinBox_green = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_green.setMaximum(255)
        self.spinBox_green.setObjectName("spinBox_green")
        self.horizontalLayout_5.addWidget(self.spinBox_green)
        self.spinBox_blue = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_blue.setMaximum(255)
        self.spinBox_blue.setObjectName("spinBox_blue")
        self.horizontalLayout_5.addWidget(self.spinBox_blue)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 490, 341, 301))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 90, 301, 141))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.freq_dial = QtWidgets.QSlider(self.groupBox_2)
        self.freq_dial.setGeometry(QtCore.QRect(29, 70, 231, 22))
        self.freq_dial.setMouseTracking(False)
        self.freq_dial.setTabletTracking(True)
        self.freq_dial.setMinimum(10)
        self.freq_dial.setMaximum(65)
        self.freq_dial.setSingleStep(5)
        self.freq_dial.setProperty("value", 10)
        self.freq_dial.setOrientation(QtCore.Qt.Horizontal)
        self.freq_dial.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.freq_dial.setObjectName("freq_dial")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(240, 100, 55, 16))
        self.label_6.setObjectName("label_6")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(120, 110, 42, 22))
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(65)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(170, 110, 55, 21))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 195, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.on_b = QtWidgets.QPushButton(self.layoutWidget4)
        self.on_b.setObjectName("on_b")
        self.horizontalLayout_4.addWidget(self.on_b)
        self.off_b = QtWidgets.QPushButton(self.layoutWidget4)
        self.off_b.setObjectName("off_b")
        self.horizontalLayout_4.addWidget(self.off_b)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 230, 301, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fix_point_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fix_point_button.setObjectName("fix_point_button")
        self.verticalLayout.addWidget(self.fix_point_button)
        self.save_button = QtWidgets.QPushButton(self.groupBox_4)
        self.save_button.setGeometry(QtCore.QRect(0, 270, 341, 29))
        self.save_button.setObjectName("save_button")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 60, 1231, 821))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.escape_but = QtWidgets.QPushButton(self.centralwidget)
        self.escape_but.setGeometry(QtCore.QRect(0, 0, 151, 29))
        self.escape_but.setObjectName("escape_but")
        self.point_label = QtWidgets.QLabel(self.centralwidget)
        self.point_label.setGeometry(QtCore.QRect(180, 800, 161, 16))
        self.point_label.setObjectName("point_label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 50, 73, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FilEye"))
        self.open_port_but.setText(_translate("MainWindow", "Open"))
        self.close_port_but.setText(_translate("MainWindow", "Close"))
        self.groupBox.setTitle(_translate("MainWindow", "        Color control"))
        self.label.setText(_translate("MainWindow", "     Red"))
        self.label_2.setText(_translate("MainWindow", "  Green"))
        self.label_3.setText(_translate("MainWindow", "  Blue"))
        self.label_4.setText(_translate("MainWindow", "Port"))
        self.groupBox_4.setTitle(_translate("MainWindow", "    Frequency control"))
        self.label_5.setText(_translate("MainWindow", "10 Гц"))
        self.label_6.setText(_translate("MainWindow", "65 Гц"))
        self.label_8.setText(_translate("MainWindow", "Гц"))
        self.groupBox_3.setTitle(_translate("MainWindow", "On/Off frequency"))
        self.on_b.setText(_translate("MainWindow", "on"))
        self.off_b.setText(_translate("MainWindow", "off"))
        self.fix_point_button.setText(_translate("MainWindow", "Fix point"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.label_7.setText(_translate("MainWindow", "Graphic :"))
        self.escape_but.setText(_translate("MainWindow", "Main window"))
        self.point_label.setText(_translate("MainWindow", "Осталось точек: 7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
