# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registration_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_reg(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 657)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(240, 235, 190)\n"
"}\n"
"QPushButton{\n"
"    background-color:rgb(182, 217, 157);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;        \n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(147, 204, 105);\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px    \n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(182, 217, 157);\n"
"    padding: 6px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    margin: 0 -4px;\n"
"    \n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.registration_but = QtWidgets.QPushButton(self.centralwidget)
        self.registration_but.setGeometry(QtCore.QRect(240, 460, 611, 28))
        self.registration_but.setObjectName("registration_but")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 180, 101, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(340, 166, 501, 281))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.surname_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.surname_edit.setObjectName("surname_edit")
        self.verticalLayout.addWidget(self.surname_edit)
        self.name_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.name_edit.setObjectName("name_edit")
        self.verticalLayout.addWidget(self.name_edit)
        self.patronymic_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.patronymic_edit.setObjectName("patronymic_edit")
        self.verticalLayout.addWidget(self.patronymic_edit)
        self.group_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.group_edit.setObjectName("group_edit")
        self.verticalLayout.addWidget(self.group_edit)
        self.gender_edit = QtWidgets.QComboBox(self.layoutWidget_2)
        self.gender_edit.setObjectName("gender_edit")
        self.gender_edit.addItem("")
        self.gender_edit.addItem("")
        self.gender_edit.addItem("")
        self.verticalLayout.addWidget(self.gender_edit)
        self.cancel_but = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_but.setGeometry(QtCore.QRect(240, 510, 611, 28))
        self.cancel_but.setObjectName("cancel_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FilEye"))
        self.registration_but.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "    Фамилия"))
        self.label_2.setText(_translate("MainWindow", "      Имя"))
        self.label.setText(_translate("MainWindow", "    Отчество"))
        self.label_5.setText(_translate("MainWindow", "  Номер группы"))
        self.label_6.setText(_translate("MainWindow", "         Пол"))
        self.gender_edit.setItemText(0, _translate("MainWindow", "Выбрать..."))
        self.gender_edit.setItemText(1, _translate("MainWindow", "Мужской"))
        self.gender_edit.setItemText(2, _translate("MainWindow", "Женский"))
        self.cancel_but.setText(_translate("MainWindow", "Cancel"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow_reg()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
